config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # URLから"/public"を取り除くために"scope module"を使用
  scope module: :public do
    root "homes#top"
    get "home/about" => "homes#about", as: "about"
    resources :users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      member do
        get :followings, :followers
      end
      member do
        get :favorites
      end
    end

    resources :health_records, only: [:index, :new, :show, :create, :edit, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :health_record_comments, only: [:create, :edit, :destroy]
    end
    get "search", to: "searches#search"
    get "search_tag" => "health_records#search_tag"
    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :group_users, only: [:create, :destroy]
      get "new/mail" => "groups#new_mail"
      get "send/mail" => "groups#send_mail"
    end
  end

  # 管理者側は/adminをURLに組み込みわかりやすくするため"namespace"を使用
  namespace :admin do
    root "homes#top"
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :health_records, only: [:index, :edit, :destroy]
    resources :health_record_comments, only: [:index, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :record_tags, only: [:index, :destroy]
    resources :groups, only: [:index, :destroy]
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  # 投稿する際にジャンル名を取得する必要があるため
  belongs_to :health_record, optional: true
  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :set_genre, only: [:edit, :update]

  def index
    @genres = Genre.order(created_at: :desc)
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "You have successfully registered the genre."
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      flash.now[:alert] = "You have failed to register the genre."
      render :index
    end
  end

  def update
    if @genre.update(genre_params)
      flash[:notice] = "You have successfully updated the genre."
      redirect_to admin_genres_path
    else
      flash.now[:alert] = "You have failed to update the genre."
      render :edit
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    flash[:notice] = "You have successfully deleted the genre."
    redirect_to admin_genres_path
  end

  private
    def set_genre
      @genre = Genre.find(params[:id])
    end

    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/helpers/admin/genres_helper.rb
# frozen_string_literal: true

module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<h1 class="text-center mt-4">Editing Genres</h1>

<div class="row justify-content-center mt-4">
  <div class="col-md-6">
    <%= form_with model: @genre, url: admin_genre_path(@genre), method: :patch, class: 'form-group' do |f| %>
      <%= f.label :name, "genre name", class: 'form-label' %>
      <div class="input-group mb-3">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Please input genre name. ' %>
        <div class="input-group-append">
          <%= f.submit "save changes", class: 'btn btn-outline-success btn-sm' %>
          <%= link_to "Destroy", admin_genre_path(@genre.id), method: :delete, data: { confirm: 'Are you sure really?' }, class: "btn btn-outline-danger btn-sm" %>
          <%= link_to "Back", admin_genres_path , class: "btn btn-outline-secondary btn-sm" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="mt-2 text-danger">
  <% if @genre.errors.any? %>
    <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div class="container mt-5">
  <div class="col-md-12 mx-auto">
    <div class="row col-lg-8 justify-content-left">
      <h1><strong>Genres List and Adding</strong></h1>
    </div>
  </div>
</div>

<div class="row justify-content-center mt-4">
  <div class="col-md-6">
    <%= form_with model: @genre, url: admin_genres_path, class: 'form-group' do |f| %>
      <%= f.label :name, "genre name", class: 'form-label' %>
      <div class="input-group mb-3">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Please input genre name.' %>
        <div class="input-group-append">
          <%= f.submit "create genre", class: 'btn btn-outline-success' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row justify-content-center mt-4">
  <div class="col-md-7">
    <table class="table table-borderless">
      <thead>
        <tr>
          <th>Genre Name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to 'edit', edit_admin_genre_path(genre), class: 'btn btn-outline-success btn-sm' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>