config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # URLから"/public"を取り除くために"scope module"を使用
  scope module: :public do
    root "homes#top"
    get "home/about" => "homes#about", as: "about"
    resources :users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      member do
        get :followings, :followers
      end
      member do
        get :favorites
      end
    end

    resources :health_records, only: [:index, :new, :show, :create, :edit, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :health_record_comments, only: [:create, :edit, :destroy]
    end
    get "search", to: "searches#search"
    get "search_tag" => "health_records#search_tag"
    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :group_users, only: [:create, :destroy]
      get "new/mail" => "groups#new_mail"
      get "send/mail" => "groups#send_mail"
    end
  end

  # 管理者側は/adminをURLに組み込みわかりやすくするため"namespace"を使用
  namespace :admin do
    root "homes#top"
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :health_records, only: [:index, :edit, :destroy]
    resources :health_record_comments, only: [:index, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :record_tags, only: [:index, :destroy]
    resources :groups, only: [:index, :destroy]
  end
end

app/models/health_record.rb
class HealthRecord < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :favorites, dependent: :destroy

  has_many :health_record_comments, dependent: :destroy

  has_many :health_record_tags, dependent: :destroy
  has_many :record_tags, through: :health_record_tags

  belongs_to :genre

  validates :exercise, presence: true, length: { maximum: 50 }
  validates :training_content, presence: true, length: { maximum: 50 }
  validates :diet_content, presence: true, length: { maximum: 50 }
  validates :today_impression, presence: true, length: { maximum: 100 }
  validates :tag_name, presence: true, length: { maximum: 20 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  # 部分検索や前方一致など分けて検索させたいため記述
  def self.looks(search, word)
    if search == "perfect_match"
      @health_records = HealthRecord.joins(:genre).where("genres.name LIKE ?", "%#{word}%")
    elsif search == "forward_match"
      @health_records = HealthRecord.joins(:genre).where("genres.name LIKE ?", "#{word}%")
    elsif search == "backward_match"
      @health_records = HealthRecord.joins(:genre).where("genres.name LIKE ?", "%#{word}")
    elsif search == "partial_match"
      @health_records = HealthRecord.joins(:genre).where("genres.name LIKE ?", "%#{word}%")
    else
      @health_records = HealthRecord.all
    end
  end
  
  # 既存のタグと新しいタグを選別するために記述
  def save_record_tags(tags)
    current_tags = self.record_tags.pluck(:tag_name) unless self.record_tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    old_tags.each do |old_name|
      self.record_tags.delete RecordTag.find_by(tag_name: old_name)
    end

    new_tags.each do |new_name|
      record_tag = RecordTag.find_or_create_by(tag_name: new_name)
      self.record_tags << record_tag
    end
  end
end

app/controllers/admin/health_records_controller.rb
class Admin::HealthRecordsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @health_records = HealthRecord.order(created_at: :desc).page(params[:page].to_i)
  end

  def edit
    @health_record = HealthRecord.find(params[:id])
  end

  def destroy
    @health_record = HealthRecord.find(params[:id])
    @health_record.destroy
    flash[:notice] = "You have successfully deleted the record."
    redirect_to admin_health_records_path
  end

  private
    def health_record_params
      params.require(:health_record).permit(:name, :genre_id, :exercise, :training_content, :diet_content, :today_impression)
    end
end

app/helpers/admin/health_records_helper.rb
# frozen_string_literal: true

module Admin::HealthRecordsHelper
end

app/views/admin/health_records/edit.html.erb
<div class="container mt-5">
  <div class="col-md-12 mx-auto">
    <div class="row col-lg-8 justify-content-left">
      <h1><strong>Editing Record Details of Admin</strong></h1>
    </div>
  </div>

  <div class="col-md-12 mt-5">
    <table class="table table-borderless">
      <tbody>
        <tr>
          <td><strong>Posted User</strong></td>
          <td>
            <%= @health_record.user.name %>
          </td>
        </tr>
        <tr>
          <td><strong>Body Parts</strong></td>
          <td>
            <%= @health_record.genre.name %>
          </td>
        </tr>
        <tr>
          <td><strong>Exercise</strong></td>
          <td>
            <%= @health_record.exercise %>
          </td>
        </tr>
        <tr>
          <td>
            <strong>
              Training Contents
            </strong>
          </td>
          <td>
            <%= @health_record.training_content %>
          </td>
        </tr>
        <tr>
          <td><strong>Diet Contents</strong></td>
          <td>
            <%= @health_record.diet_content %>
          </td>
        </tr>
        <tr>
          <td><strong>Today's impressions</strong></td>
          <td>
            <%= @health_record.today_impression %>
          </td>
        </tr>
        <tr>
          <td><strong>Posted Time</strong></td>
          <td>
            <i class="far fa-clock"></i><%= @health_record.created_at.strftime("%a %Y.%m.%d %H:%M") %>
          </td>
        </tr>
        <tr>
          <td></td>
          <td>
            <%= link_to "Destroy", admin_health_record_path(@health_record.id), method: :delete, 
            data: { confirm: 'Are you sure really?' }, class: "btn btn-outline-danger btn-sm mr-3" %>
            <%= link_to "Back", admin_health_records_path, class: "btn btn-outline-secondary btn-sm mr-3" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/health_records/index.html.erb
<div class="container mt-5">
  <div class="col-md-12 mx-auto">
    <div class="row col-lg-8 justify-content-left">
      <h1><strong>All Records</strong></h1>
    </div>
  </div>

  <div class="col-md-12">
    <table class="table table-borderless">
      <thead>
        <tr>
          <th></th>
          <th>Posted User</th>
          <th>Body Parts</th>
          <th>Posted Time</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @health_records.each do |health_record| %>
          <tr>
            <td>
              <%= image_tag health_record.user.get_profile_image, size: "30x30" %>
            </td>
            <td>
              <%= health_record.user.name %>
            </td>
            <td>
              <%= health_record.genre.name %>
            </td>
            <td>
              <i class="far fa-clock"></i><%= health_record.created_at.strftime("%a %Y.%m.%d %H:%M") %>
            </td>
            <td>
              <%= link_to "Edit", edit_admin_health_record_path(health_record.id), class: "btn btn-outline-success btn-sm" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="d-flex justify-content-center mt-5">
  <%= paginate @health_records, theme: 'twitter-bootstrap-4' %>
</div>