config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # URLから"/public"を取り除くために"scope module"を使用
  scope module: :public do
    root "homes#top"
    get "home/about" => "homes#about", as: "about"
    resources :users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      member do
        get :followings, :followers
      end
      member do
        get :favorites
      end
    end

    resources :health_records, only: [:index, :new, :show, :create, :edit, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :health_record_comments, only: [:create, :edit, :destroy]
    end
    get "search", to: "searches#search"
    get "search_tag" => "health_records#search_tag"
    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :group_users, only: [:create, :destroy]
      get "new/mail" => "groups#new_mail"
      get "send/mail" => "groups#send_mail"
    end
  end

  # 管理者側は/adminをURLに組み込みわかりやすくするため"namespace"を使用
  namespace :admin do
    root "homes#top"
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :health_records, only: [:index, :edit, :destroy]
    resources :health_record_comments, only: [:index, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :record_tags, only: [:index, :destroy]
    resources :groups, only: [:index, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :validatable

  has_many :health_records, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :health_record_comments, dependent: :destroy

  # フォローしている関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローされている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # フォローしているユーザーを取得
  has_many :followings, through: :active_relationships , source: :followed
  # フォロワーを取得
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy
  has_many :owned_groups, class_name: "Group"

  validates :name, presence: true, length: {maximum: 50}
  validates :introduction, length: {maximum: 50}
  validates :target, length: {maximum: 50}

  def get_profile_image
    (profile_image.attached?) ? profile_image : "no_image.jpg"
  end

  # フォロー実行
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  # フォロー解除
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  # フォローしているか？
  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  GUEST_USER_EMAIL = "guest@example.com"
    def self.guest
      find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
        user.password = SecureRandom.urlsafe_base64
        user.name = "Guest User"
        user.introduction = "hello"
        user.target = "hello"
      end
    end

    def guest_user?
      email == GUEST_USER_EMAIL
    end

  def user_status
    if is_active == true
      "available"
    else
      "unavailable"
    end
  end

  def active_for_authentication?
    super && (is_active == true)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.order(created_at: :desc).page(params[:page].to_i)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have successfully updated the user information."
      redirect_to edit_admin_user_path(@user)
    else
      flash.now[:alert] = "You have failed to update the user information."
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "You have successfully deleted the user."
    redirect_to admin_users_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :is_active)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "You logged in as a Guest User."
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container mt-5">
  <div class="col-md-12 mx-auto">
    <div class="row col-lg-8 justify-content-left">
      <h1><strong>Editing User Details of Admin</strong></h1>
    </div>
  </div>

  <div class="col-md-12 mt-5">
    <%= form_with model: [:admin, @user] do |f| %>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td><strong>User Name</strong></td>
            <td>
              <%= @user.name %>
            </td>
          </tr>
          <tr>
            <td><strong>Introduction</strong></td>
            <td>
              <%= @user.introduction %>
            </td>
          </tr>
          <tr>
            <td><strong>Target</strong></td>
            <td>
              <%= @user.target %>
            </td>
          </tr>
          <tr>
            <td><strong>Joined Day</strong></td>
            <td>
              <i class="far fa-clock"></i><%= @user.created_at.strftime("%a %Y.%m.%d %H:%M") %>
            </td>
          </tr>
          <tr>
            <td><strong>User Status</strong></td>
            <td>
              <%= f.radio_button :is_active, :true %>
              <%= f.label :is_active, "available", { value: :true }  %>

              <%= f.radio_button :is_active, :false %>
              <%= f.label :is_active, "unavailable", { value: :false } %>
            </td>
          </tr>
          <tr>
            <td></td>
            <td>
              <%= f.submit "Save Changes", class: "btn btn-outline-success btn-sm mr-3" %>
              <%= link_to "Destroy", admin_user_path(@user.id), method: :delete, 
              data: { confirm: 'Are you sure really?' }, class: "btn btn-outline-danger btn-sm mr-3" %>
              <%= link_to "Back", admin_users_path, class: "btn btn-outline-secondary btn-sm mr-3" %>
            </td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container mt-5">
  <div class="col-md-12 mx-auto">
    <div class="row col-lg-8 justify-content-left">
      <h1><strong>All Users</strong></h1>
    </div>
  </div>

  <div class="col-md-12">
    <table class="table table-borderless">
      <thead>
        <tr>
          <th></th>
          <th>User Name</th>
          <th>Introduction</th>
          <th>Joined Day</th>
          <th>User Status</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= image_tag user.get_profile_image, size: "30x30" %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= user.introduction %>
            </td>
            <td>
              <i class="far fa-clock"></i><%= user.created_at.strftime("%a %Y.%m.%d %H:%M") %>
            </td>
            <td>
              <% if user.is_active == true %>
                <strong class="text-success">
                  <%= user.user_status %>
                </strong>
              <% else %>
                <strong class="text-danger">
                  <%= user.user_status %>
                </strong>
              <% end %>
            </td>
            <td>
              <%= link_to "Edit", edit_admin_user_path(user.id), class: "btn btn-outline-success btn-sm" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="d-flex justify-content-center mt-5">
  <%= paginate @users, theme: 'twitter-bootstrap-4' %>
</div>