config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # URLから"/public"を取り除くために"scope module"を使用
  scope module: :public do
    root "homes#top"
    get "home/about" => "homes#about", as: "about"
    resources :users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      member do
        get :followings, :followers
      end
      member do
        get :favorites
      end
    end

    resources :health_records, only: [:index, :new, :show, :create, :edit, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :health_record_comments, only: [:create, :edit, :destroy]
    end
    get "search", to: "searches#search"
    get "search_tag" => "health_records#search_tag"
    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :group_users, only: [:create, :destroy]
      get "new/mail" => "groups#new_mail"
      get "send/mail" => "groups#send_mail"
    end
  end

  # 管理者側は/adminをURLに組み込みわかりやすくするため"namespace"を使用
  namespace :admin do
    root "homes#top"
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :health_records, only: [:index, :edit, :destroy]
    resources :health_record_comments, only: [:index, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :record_tags, only: [:index, :destroy]
    resources :groups, only: [:index, :destroy]
  end
end

app/views/layouts/_footer.html.erb
<div class="container bg-secondary">
  <div class="row">
    <div class="col pt-3 text-center text-light">
      <p><i class="fa-solid fa-person-running"></i>Wellness_Journey.inc<i class="fa-solid fa-person-running"></i></p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-secondary text-light">
  <a class="navbar-brand text-light" href="/"><i class="fa-solid fa-dumbbell"></i>WellnessJourney<i class="fa-solid fa-dumbbell"></i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    <% if admin_signed_in? %>

      <li class="nav-item">
        <%= link_to admin_root_path, class: 'nav-link text-light' do %>
          <i class="fa-solid fa-user-tie"></i>Admin Top
        <% end %>
      </li>

      <li>
        <%= link_to admin_genres_path, class: 'nav-link text-light' do %>
          <i class="fa-solid fa-list"></i>Genres
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to admin_users_path, class: 'nav-link text-light' do %>
          <i class="fa-solid fa-address-book"></i>Users
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to admin_health_records_path, class: "nav-link text-light" do %>
          <i class="fa-solid fa-file-pen"></i>Records
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to admin_health_record_comments_path, class: "nav-link text-light" do %>
          <i class="fa-solid fa-comments"></i>Comments
        <% end %>
      </li>

      <li>
        <%= link_to admin_record_tags_path, class: "nav-link text-light" do %>
          <i class="fa-solid fa-tags"></i>Tags
        <% end %>
      </li>

      <li>
        <%= link_to admin_groups_path, class: "nav-link text-light" do %>
          <i class="fa-solid fa-people-group"></i>Groups
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
          <i class="fa-solid fa-arrow-right-from-bracket"></i>Log out
        <% end %>
      </li>

    <% elsif user_signed_in? %>

      <li class="nav-item">
        <%= link_to users_path, class: 'nav-link text-light' do %>
          <i class="fa-solid fa-users"></i>Users
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to health_records_path, class: 'nav-link text-light' do %>
          <i class="fa-solid fa-file-pen"></i>Records
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to  new_health_record_path, class: 'nav-link text-light' do %>
          <i class="fa-solid fa-plus"></i>New Recording
        <% end %>
      </li>

      <li>
        <%= link_to new_group_path, class: 'nav-link text-light' do %>
          <i class="fa-solid fa-group-arrows-rotate"></i>New Grouping
        <% end %>
      </li>

      <li>
        <%= link_to groups_path, class: 'nav-link text-light' do %>
          <i class="fa-solid fa-user-group"></i>Groups
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do  %>
          <i class="fa-solid fa-arrow-right-from-bracket"></i>Log out
        <% end %>
      </li>

    <% else %>

      <li class="nav-item">
        <%= link_to about_path, class: 'nav-link text-light' do %>
          <i class="fa-brands fa-readme"></i>About
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
          <i class="fa-solid fa-user-plus"></i>Sign up
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
          <i class="fa-solid fa-arrow-right-to-bracket"></i> User's Log in
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to new_admin_session_path, class: 'nav-link text-light' do %>
          <i class="fa-brands fa-black-tie"></i> Admin's Log in
        <% end %>
      </li>

    <% end %>
    </ul>

    <% if admin_signed_in? %>
      <h4 class="text-warning mt-3 ml-auto mr-5">
        Admin Logging in now.
      </h4>
    <% elsif user_signed_in? %>
      <h6 class="text-light mt-3 ml-auto mr-5">
        ようこそ！<%= current_user.name %>さん!
      </h6>
    <% end %>

    <% if user_signed_in? %>
      <div class="search_form">
        <%= form_with url: search_path, local: true, method: :get do |f| %>
          <%= f.text_field :word, placeholder: "search", class: "form-control mr-sm-2" %>
          <%= f.select :range, options_for_select([['User'], ['Record']]), class: "form-control mr-sm-2" %>
          <%= f.select :search, options_for_select([["部分一致","partial_match"], ["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"]]), class: "form-control mr-sm-2" %>
          <%= f.button(type: "submit", class: "btn btn-outline-light my-2 my-sm-0 mt-2") do %>
            <i class="fa-solid fa-magnifying-glass"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WellnessJourney</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/c6847128c5.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="fontfamily: cursive;">
    <div class="footer_adjustments">
      <header>
        <%= render "layouts/header" %>
      </header>
      <main>
        <div class="text-center mt-2">
          <% flash.each do |message_type, message| %>
            <div class="flash-message <%= message_type %>"><%= message %>
              <button type="button" class="close">&times;</button>
            </div>
          <% end %>
        </div>
        <%= yield %>
      </main>
      <footer>
        <%= render "layouts/footer" %>
      </footer>
    </div>
  </body>
</html>